import { apiClient } from "@/lib/axios";

export interface ExportQuery {
  search?: string;
  filters?: Record<string, string | boolean | undefined>;
}

/**
 * Downloads an Excel (.xlsx) file generated by the backend (the `/export`
 * endpoint of each module). The active search term and filters are passed
 * the same way as for the paginated list, so the export always matches
 * exactly what's currently on screen.
 */
export async function downloadSpreadsheet(
  url: string,
  query: ExportQuery | undefined,
  defaultFilename: string
): Promise<void> {
  const params: Record<string, unknown> = {};
  if (query?.search) params.search = query.search;
  if (query?.filters) {
    for (const [key, value] of Object.entries(query.filters)) {
      if (value !== undefined && value !== "") params[key] = value;
    }
  }

  const { data, headers } = await apiClient.get<Blob>(url, {
    params,
    responseType: "blob",
  });

  const filename = parseContentDispositionFilename(headers["content-disposition"]) ?? defaultFilename;
  const objectUrl = URL.createObjectURL(data);
  const link = document.createElement("a");
  link.href = objectUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(objectUrl);
}

function parseContentDispositionFilename(header: unknown): string | null {
  if (typeof header !== "string") return null;
  const match = header.match(/filename="?([^";]+)"?/i);
  return match?.[1] ?? null;
}
